PDF_URLS = {
    "jpmorgan_annual_report_2024.pdf":
        "https://www.jpmorganchase.com/content/dam/jpmc/jpmorgan-chase-and-co/investor-relations/documents/annualreport-2024.pdf",
    "bofa_annual_report_2024.pdf":
        "https://www.sec.gov/Archives/edgar/data/70858/000007085825000155/bofaannualreport2024.pdf",
    "wellsfargo_annual_report_2024.pdf":
        "https://www.wellsfargo.com/assets/pdf/about/investor-relations/annual-reports/2024-annual-report.pdf",
    "citigroup_annual_report_2024.pdf":
        "https://www.citigroup.com/rcs/citigpa/storage/public/citi-2024-annual-report.pdf",
    "goldmansachs_annual_report_2024.pdf":
        "https://www.goldmansachs.com/investor-relations/financials/current/annual-reports/2024-annual-report/multimedia/2024-annual-report.pdf",
    "morganstanley_annual_report_2024.pdf":
        "https://www.morganstanley.com/content/dam/msdotcom/en/about-us-ir/pdf/MSESE_Annual_Report_2024.pdf",
    "jpmorgan_annual_report_2023.pdf":
        "https://www.jpmorganchase.com/content/dam/jpmc/jpmorgan-chase-and-co/investor-relations/documents/annualreport-2023.pdf",
    "jpmorgan_10k_sec_2023.pdf":
        "https://www.sec.gov/Archives/edgar/data/19617/000001961724000311/annualreport-2023.pdf",
    "bis_basel3_monitoring_mar2025.pdf":
        "https://www.bis.org/bcbs/publ/d592.pdf",
    "bis_basel3_monitoring_oct2025.pdf":
        "https://www.bis.org/bcbs/publ/d599.pdf",
    "bis_credit_risk_principles_2025.pdf":
        "https://www.bis.org/bcbs/publ/d595.pdf",
    "bis_supervisory_effectiveness_2025.pdf":
        "https://www.bis.org/bcbs/publ/wp45.pdf",
    "bis_basel3_finalising_reforms.pdf":
        "https://www.bis.org/bcbs/publ/d424.pdf",
    "bis_basel3_summary.pdf":
        "https://www.bis.org/bcbs/publ/d424_hlsummary.pdf",
    "bis_basel_framework_full.pdf":
        "https://www.bis.org/baselframework/BaselFramework.pdf",
    "bis_core_principles_banking.pdf":
        "https://www.bis.org/publ/bcbs230.pdf",
    "bis_operational_resilience.pdf":
        "https://www.bis.org/bcbs/publ/d516.pdf",
    "bis_climate_risk_banks.pdf":
        "https://www.bis.org/bcbs/publ/d532.pdf",
    "fatf_financial_inclusion_2025.pdf":
        "https://www.fatf-gafi.org/content/dam/fatf-gafi/guidance/Guidance-Financial-Inclusion%20-Anti-Money-Laundering-Terrorist-Financing-Measures.pdf.coredownload.pdf",
    "fatf_recommendations.pdf":
        "https://www.fatf-gafi.org/content/dam/fatf-gafi/recommendations/FATF%20Recommendations%202012.pdf.coredownload.inline.pdf",
    "fatf_rba_banking_sector.pdf":
        "https://www.fatf-gafi.org/content/dam/fatf-gafi/guidance/RBA-Banking-Sector.pdf.coredownload.inline.pdf",
    "fatf_universal_procedures_2023.pdf":
        "https://www.fatf-gafi.org/content/dam/fatf-gafi/methodology/Universal-Procedures-2023.pdf.coredownload.inline.pdf",
    "fed_supervision_report_dec2025.pdf":
        "https://www.federalreserve.gov/publications/files/202512-supervision-and-regulation-report.pdf",
    "fed_sr1107_model_risk.pdf":
        "https://www.federalreserve.gov/supervisionreg/srletters/sr1107a1.pdf",
    "fed_sr1217_large_fi_supervision.pdf":
        "https://www.federalreserve.gov/supervisionreg/srletters/sr1217.pdf",
    "occ_bank_supervision_process.pdf":
        "https://www.occ.gov/publications-and-resources/publications/comptrollers-handbook/files/bank-supervision-process/pub-ch-bank-supervision-process.pdf",
    "occ_community_bank_supervision.pdf":
        "https://www.occ.gov/publications-and-resources/publications/comptrollers-handbook/files/community-bank-supervision/pub-ch-community-bank-supervision.pdf",
    "occ_problem_bank_supervision.pdf":
        "https://www.occ.gov/publications-and-resources/publications/comptrollers-handbook/files/problem-bank-supervision/pub-ch-problem-bank-supervision.pdf",
    "occ_large_bank_supervision.pdf":
        "https://www.occ.gov/publications-and-resources/publications/comptrollers-handbook/files/large-bank-supervision/pub-ch-large-bank-supervision.pdf",
    "fincen_amlcft_program_nprm_2024.pdf":
        "https://www.fincen.gov/system/files/shared/Program-NPRM-FactSheet-508.pdf",
    "fincen_investment_adviser_rule_2024.pdf":
        "https://www.fincen.gov/system/files/shared/IAFinalRuleFactSheet-FINAL-508.pdf",
    "fincen_fy2025_budget.pdf":
        "https://home.treasury.gov/system/files/266/12.-FinCEN-FY-2025-CJ.pdf",
    "ffiec_bsa_aml_manual.pdf":
        "https://www.ffiec.gov/press/pdf/FFIEC%20BSA-AML%20Exam%20Manual.pdf",
}
